# Generated by Django 4.0.2 on 2022-02-12 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Malware',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('digest', models.TextField()),
                ('whitelisted', models.BooleanField(default=False)),
            ],
        ),
    ]
